plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

// Qdrant Edge for Android: UniFFI bindings generated by native/build-qdrant-edge.sh
// (package tech.qdrant.edge.ffi) plus PolyCare's VectorStore adapter on top of them.
android {
    namespace = "org.polycare.vector.edge"
    compileSdk = 35

    defaultConfig {
        minSdk = 29
        ndk { abiFilters += "arm64-v8a" }
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
        // Generated UniFFI code is not ours to lint.
        suppressWarnings = true
    }
}

dependencies {
    api(project(":core-vector"))
    implementation(libs.jna) { artifact { type = "aar" } }
    implementation(libs.kotlinx.coroutines.android)

    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.kotlinx.coroutines.test)
}
